#%Module1.0
proc ModulesHelp { } {
        puts stderr "\tAdds dDocent dependencies to environment."
}

module-whatis "Adds dDocent dependencies to environment."

prepend-path    PATH            /gscratch/srlab/programs/freebayes-v1.3.0-1/freebayes-v1.3.0-1
prepend-path    PATH            /gscratch/srlab/programs/Trimmomatic-0.33
prepend-path    PATH            /gscratch/srlab/programs/stacks-2.41
prepend-path    PATH            /gscratch/srlab/programs/bwa-0.7.17
prepend-path    PATH            /gscratch/srlab/programs/vcftools-0.1.16/bin
prepend-path    PATH            /gscratch/srlab/programs/rainbow_2.0.4
prepend-path    PATH            /gscratch/srlab/programs/seqtk-1.3
prepend-path    PATH            /gscratch/srlab/programs/samtools-1.9
prepend-path    PATH            /gscratch/srlab/programs/cd-hit-v4.8.1-2019-0228
prepend-path    PATH            /gscratch/srlab/programs/bedtools-2.27.1/bin
prepend-path    PATH            /gscratch/srlab/programs/vcflib/bin
prepend-path    PATH            /gscratch/srlab/programs/parallel-20190922/src
prepend-path    PATH            /gscratch/srlab/programs/bamtools-2.5.1/usr/local/bin
prepend-path    PATH            /gscratch/srlab/programs/pear-0.9.11-linux-x86_64/bin
prepend-path    PATH            /gscratch/srlab/programs/fastp-0.20.0
prepend-path    PATH            /gscratch/srlab/programs/mawk-1.3.4-20190203
