#%Module1.0
proc ModulesHelp { } {
        puts stderr "\tAdds DRAP programs to environment."
}

module-whatis "Adds DRAP programs to environment."

prepend-path    PATH            /gscratch/srlab/programs/DRAP/bedtools-2.26.0/bin
prepend-path    PATH            /gscratch/srlab/programs/blat-v36x2
prepend-path    PATH            /gscratch/srlab/programs/bowtie2-2.3.4.1-linux-x86_64
prepend-path    PATH            /gscratch/srlab/programs/busco-v3/scripts
prepend-path    PATH            /gscratch/srlab/programs/bwa-0.7.17
prepend-path    PATH            /gscratch/srlab/programs/cd-hit-v4.8.1-2019-0228
prepend-path    PATH            /gscratch/srlab/programs/miniconda3/bin
prepend-path    PATH            /gscratch/srlab/programs/exonerate-2.2.0-x86_64/bin
prepend-path    PATH            /gscratch/srlab/programs/express-1.5.1-linux_x86_64
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
prepend-path    PATH
